import numpy as np
import matplotlib.pyplot as plt

import importlib.util
from pathlib import Path

# Load box_muller function from the practical proof file
proof_file = Path(__file__).with_name("Practicle_proof_of_Box_Mullar.py")
spec = importlib.util.spec_from_file_location("Practicle_proof_of_Box_Mullar", proof_file)
practical_proof = importlib.util.module_from_spec(spec)
spec.loader.exec_module(practical_proof)

Z1, Z2 = practical_proof.box_muller(n=10000)

# Histogram of Z1
plt.figure()
plt.hist(Z1, bins=50, density=True, alpha=0.7)

x = np.linspace(-4, 4, 300)
normal_pdf = (1 / np.sqrt(2 * np.pi)) * np.exp(-x**2 / 2)

plt.plot(x, normal_pdf)
plt.title("Box-Muller Generated Standard Normal Samples")
plt.xlabel("z")
plt.ylabel("Density")
plt.show()

# Scatter plot of pairs
plt.figure()
plt.scatter(Z1[:1000], Z2[:1000], s=5)
plt.title("Pairs Generated by Box-Muller")
plt.xlabel("Z1")
plt.ylabel("Z2")
plt.axis("equal")
plt.show()